version: '3'

services:
  mongodb:
    image: 'mongo'
    container_name: 'shoppart-mongo-db'
    environment:
      - MONGO_INITDB_ROOT_DATABASE=shopparty
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./.data:/data/db
    ports:
      - '27017:27017'



